changelogs/unreleased/--238p38r.yml
src/theme/variables.css

Updated color of ion-icon in ion-chip, ion-chip outline and ion-item lines in dark mode(#238p38r)

---

src/store/modules/user/actions.ts
src/store/modules/user/index.ts
src/store/modules/user/mutations.ts

Closes #
Worked on improving the code to remove the None option from shop which is set by default by us when a user is trying to log in and used first store/shop selected by default when a user is logging in initially.
**Screenshots:**
- Settings page:

Improved: code to remove 'None' as shop option from settings page (#29wgty7).

---

src/components/ProductFilterModal.vue

Closes #
:- Worked on improving the code to assign input field to instance variable for searchbar.
Because when performing any action on search with enter key, the value of instance variable is set after the action is performed due to which wrong data is passed to API.

Improved: code to assign input field to instance variable for searchbar (#2cj8nc4).

---

src/components/JobHistoryModal.vue
src/views/ThresholdUpdates.vue

Closes #73 
:- Improved code to add support to show history on running and history segments.
:- Implemented functionality to add support to update job history modal.
:- Improved code to add an empty div to handle the case when we have a missing slot of flex in the actions section.

Fixed: code to handle the case when job history modal isn't updating (#2adm63m).

---

src/components/Image.vue
src/components/JobConfiguration.vue
src/store/modules/job/actions.ts
src/store/modules/user/actions.ts
src/views/Settings.vue
src/views/ThresholdUpdates.vue

**Definitions**
- `img.onerror = function (error)` 
- `import { translate } from "@/i18n";`
- `setUserInstanceUrl ({ state, commit }, payload){`
-  `async getEComStores({ commit }, payload) {`
- `async setEComStore({ commit, dispatch }, payload) {`
- `import { IonBackButton, IonButton, IonContent, IonHeader,IonIcon, IonItem, IonLabel, IonMenuButton, IonPage, IonSelect, IonSelectOption, IonTitle, IonToolbar, popoverController } from '@ionic/vue';`
- `import emitter from '@/event-bus';` 
**Assignments**
- `const cachedEnum = payload.map((id: any) => state.enumIds[id]);`
-  `const cachedTempExpr = tempExprIds.map((id: any) => state.temporalExp[id]);`

Fixed build console warnings (threshold-management/#69)

---

src/views/SelectProduct.vue

Improved code by updating padding and removing gap above result placeholder and added save threshold method to fab button in mobile view (#2cxuhuy)

---

src/components/SaveThresholdModal.vue
src/store/modules/job/actions.ts

When scheduling a job the temporal expression for the job is not being set
Closes #
Passed the field SERVICE_TEMP_EXPR when scheduling the job as this field overrides the already passed field tempExprId

Fixed: issue of temp expr not being set when scheduling a new job(#2dmgzqb)

---

src/components/ProductFilterModal.vue
src/store/modules/product/actions.ts
src/views/SelectProduct.vue

Closes #
Object with array and operator should be set on reset instead of empty array

Fixed: product filters not updating on reset, logout and store change (#2dmrnhx)

---

src/store/modules/job/actions.ts

Initially we were setting the status of Job from cached without checking if it exist
Deleted the job from cached instead of updating the status, fetchJobs action is already used to update cache with available jobs
Closes https://app.clickup.com/t/2ftb67b

Fixed: Error: Something went wrong on successful cancelling of  job (#2ftb67b)

---

src/views/ThresholdUpdates.vue

There may be possibility that threshold may be set to 0. default existence checks 0, undefined and null
Explicity added condition for null and undefined
Closes #

Fixed: threshold value 0 not displayed (#2jufac1)

---

src/components/SaveThresholdModal.vue

Closes #
we were using the productStoreId to fetch the configId, which is always undefined. 
Instead used shopifyConfig.shopifyConfigId to get shopify config id

fixed: ShopifyConfig id is undefined when making api call while scheduling the job(#2kbpaux)

---

.eslintrc.js
src/components/SaveThresholdModal.vue
src/logger/index.ts

Closes #69 
- Updated: eslint rule to disable no-console rule
- Removed: unwanted import for DateTime in save threshold modal
- Removed: unwanted paramters defined in the errorHandler

Fixed: build warnings in the app(#85zrmg3u1)

---

src/components/ProductFilterModal.vue
src/store/modules/product/actions.ts
src/views/SelectProduct.vue

Closes #193 
Added a close/check button to save the applied tag filters in the modal. Previously, the tags were applied directly on checking/selecting but now the changes will take effect after clicking the check button.
[Screencast from 10-04-23 05:45:47 PM IST.webm](https://user-images.githubusercontent.com/59442907/230899959-1a39b5c7-44f4-4251-83fa-61d6e71f39d9.webm)

Added: close button in the tag modal (#85zrvzfqv)

---

src/store/modules/user/actions.ts

Implemented: logic in try catch as in some case the logout api makes redirection, and then we are unable to parse the resp

---

src/components/Menu.vue

Fixed: Menu item is displaying as selected(#277)

---

src/components/ProductFilterModal.vue
src/views/SelectProduct.vue

https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.

Fixed: infinite scroll issue when used with searchbar(dxp-289) 

---

src/views/CreateThresholdRule.vue

Related Issue #266
Made the threshold value mandatory while creation of new rule.
Before
After 

Improved: code for making threshold value mandatory while creation (#266)

---

src/components/AddProductFacilityGroupModal.vue
src/components/AddProductFiltersModal.vue
src/components/UpdateFacilityGroupModal.vue
src/components/UpdateProductFiltersModal.vue
src/locales/en.json

Related Issue #273
Used closeOutline instead of using arrowBackOutline for maintaining consistency in modals.
Before
After

Improved: used closeOutline inside all the modal and added missing entry in translation (#273)

---

src/components/RuleItem.vue
src/store/modules/rule/actions.ts
src/views/CreateThresholdRule.vue

Related Issue #275
- Fixed total rule count not updating issue on archiving a rule.
- Added bottom line in included facility groups item.
- Added red astrick informing of required in channels selection in create rule.
Before 
After

Fixed: rules total count not updating on archiving rule, showed bottom line in rule card and required astrick in case of channels (#275)

---

src/locales/en.json
src/views/CreateShippingRule.vue
src/views/CreateStorePickupRule.vue
src/views/CreateThresholdRule.vue

Related Issue #280
Added empty state text to be shown if not channels found for a product store in rule creation pages.
Before 
After

Improved: added empty state text in the channels section in rule creation (#280)

---

src/components/ScheduleActionsPopover.vue

Related Issue #
Added the systemMessageRemoteId in payload for scheduling ruleGroup while rule now action.

Fixed: missing systemMessageRemoteId while scheduling a ruleGroup on runNow action

---

src/locales/en.json
src/services/ChannelService.ts
src/store/modules/channel/actions.ts
src/views/InventoryChannels.vue

Related Issue #302
- Improved the api fetching logic to fetch inventory channels only for the current selected product store.
- Added empty state in case of no inventory channels found.

Improved: code to fetch inventory channels based on selected product store and added empty state (#302)

---

src/components/RuleItem.vue
src/components/UpdateFacilityGroupModal.vue

Related Issue #289
- Showed group id in case of group not present in product store.
- Manually added facilityGroupId in select facility group modal to allow user unselect group not present in modal since removed from product store.
Before
After

Improved: logic to allow user unselect facility group from the rule conditions which are removed from product store. (#289)

---

src/theme/variables.css
src/views/InventoryChannels.vue
src/views/Shipping.vue
src/views/StorePickup.vue

Related Issue #305
- Improved code to bring ion-segment in line with the header title in inventory channels page.
- Fixed inventory channels not getting fetched on page refresh.
Before
After

Fixed: ion-segment not coming in line with page title in inventory-channnels page (#305)

---

src/components/AddProductFacilityGroupModal.vue
src/components/AddProductFiltersModal.vue

Related Issue #320
Added check over click event in list item of the Product filter and facility group modal to disable click event when item is already applied

Improved: disabled click event over list item if the item is already applied in another type (#320)

---

src/components/RuleItem.vue
src/views/CreateUpdateSafetyStockRule.vue
src/views/CreateUpdateShippingRule.vue

Related Issue #323
- Used selected segment from state on rule item component.
- Showed grouId when grouName is not present in create rule page.

Improved: rule item card to use selectedsegment from state and logic to show group id when name not available on create rule page (#323)

---

src/components/CreateGroupModal.vue
src/components/EditGroupModal.vue
src/components/OrderLimitPopover.vue
src/views/InventoryChannels.vue
src/views/SafetyStock.vue
src/views/Shipping.vue
src/views/StorePickup.vue
src/views/Threshold.vue

Related Issue #325
- Made inventory channel group name mandatory while editing it in edit channel group modal.
- Disabled Publish segment and hide Facility segment since both the segments are not functional.

Improved: made channel group name mandatory in edit group modal (#325)

---

src/views/InventoryChannels.vue

#334 
-  Uses v-html with replace to show descriptions with correct line breaks using <br /> tags.
- Ensures descriptions in Ionic cards are visually consistent and easy to read with formatted line breaks.
Before - 
After -

Updated: Preserved Formatting of Group Descriptions in Cards(#334)

---

src/components/RuleItem.vue
src/utils/index.ts
src/views/CreateUpdateSafetyStockRule.vue
src/views/CreateUpdateShippingRule.vue
src/views/CreateUpdateStorePickupRule.vue
src/views/CreateUpdateThresholdRule.vue

#363
- Removed multiValued field from the ruleConditions.
- Updated the ruleCondition operators from "in,not-in" to "contains,not-contains".

Improved rule condition generation template based on backend compatibility (#363)

---

src/views/InventoryChannels.vue

#374
Fixed channel header not showing up in case of no description in inventory channel.

Fixed: failing replace function in case of channels with no description (#374)

---

src/locales/en.json
src/views/InventoryChannels.vue

#384 
- Changed the ui label on  publish inventory page from 'inventory group' to 'inventory channel'

Improved: changed the inventory channel ui label on  publish inventory page(#384)
