src/components/IncludeTagsModal.vue, src/locales/en.json, src/views/SelectProduct.vue
=> Updated selectProduct page UI(#29pux36)

src/components/IncludeTagsModal.vue
closes #59
**Screenshot:**
Before:
After:
=> Fixed: code to not duplicate the result when searching on the filter lookup modal(#2a2ad3p)

src/views/ThresholdUpdates.vue
Description:
Used Id selector instead of element selector as it was selecting aside element rendered on selectProduct page.
Added CSS for animation.
=> Fixed: animation not working on initial load on thresholdUpdates page(#1ye5xcw)

src/store/modules/product/actions.ts, src/store/modules/user/actions.ts, src/views/ThresholdUpdates.vue
**Screenshot:**
Before:
After:
=> Fixed the count being reset when the product is not found on search (#2adgubh)

src/components/ProductFilterModal.vue, src/views/SelectProduct.vue
=> Changed IncludeTagsModal.vue component name to ProductFilterModal.vue (#79)

src/utils/index.ts
Closes #
Improved: position of toast from top to bottom
=> Improved: position of toast from top to bottom(#2a7ut0j)

src/views/ThresholdUpdates.vue
Description:
Updated the code to search aside element in threshold updates page instead of whole document.
=> Updated the code to search aside element in threshold updates page instead of whole document(#1ye5xcw)

src/App.vue
Closes #
:- Improved code to show Shop, Timezone and instance information at Menu bottom 
=> Improved: code to show Shop, Timezone and instance information at Menu bottom (#2d9a4ur).

src/components/ProductFilterModal.vue, src/locales/en.json, src/store/modules/product/ProductState.ts, src/store/modules/product/actions.ts, src/store/modules/product/index.ts, src/views/SelectProduct.vue
Closes #
Restructured the filter state to accommodate list as well as operator
Implemented actions to apply filters and updated query logic to honor operator
=> Implemented: added support to pass operator to product query (#2dmrnhx)

src/store/modules/product/actions.ts
#2dmha76
Closes #
https://github.com/hotwax/threshold-management/commit/ded6c5f77d84d16b58802c0f9062aeaa855daf46
Now user can see real time update in virtual & variant list if tag products does not exist
=> Fixed: When including a tag, the product count does not update if the tag does not contain any product(#2dmha76)

src/services/UserService.ts, src/store/modules/user/actions.ts
Added user preference for selected product store
Closes #
=> Implemented support to store user preference for selected product store(#2f2h90a)

src/components/ProductFilterModal.vue
Closes #
Implemented support to load more tags on infinite scroll
https://user-images.githubusercontent.com/33576503/181701682-deec4fab-6875-459e-8c48-6429121f1d6d.mp4
=> Implemented: infinite scroll support to find tag modal(#2juem0v) 

src/views/SelectProduct.vue
=> Fixed: warning icon should only be displayed if job id is paaed in route(#2ngcqdd)

src/views/SelectProduct.vue
=> Fixed: wrong value for isFilterChanged and multiple solr queries on initial load (#2ngcqdd)

src/components/JobConfiguration.vue
Closes #
https://user-images.githubusercontent.com/62360781/183347289-00c9d5a4-7861-44a5-904b-33e4de5f5ded.mov
=> Implemented: Feature to update rule name in JobConfiguration(#2p1epk4)

src/components/JobConfiguration.vue, src/store/modules/job/actions.ts, src/views/ThresholdUpdates.vue
=> Fixed: Code to update pendingJobs ruleName on thresholdUpdate page instantly(#2p1epk4)

src/components/JobConfiguration.vue
#2dmq8ja
Closes #
https://github.com/hotwax/threshold-management/commit/098d1c4e46f39bd150b3fa13eddedde15aa9a46e
Now time view will be more user friendly as it will in 12 hours format
=> Fixed: DateTime component has different hour cycle on different devices(#2dmq8ja)

src/components/SaveThresholdModal.vue
=> Fixed: Service fails when scheduled without facilityId(#2pjpbek)

src/components/SaveThresholdModal.vue, src/services/ProductService.ts
=> Implemented: Create a user search preference entry after creating search preference(#2e5ww56)

src/components/SaveThresholdModal.vue, src/services/ProductService.ts
Closes #
:- Worked on improving the code to create a user search preference entry after creating search preference (#2e5ww56).
=> Improved: code to create a user search preference entry after creating search preference (#2e5ww56).

src/components/ErrorMessageModal.vue, src/components/SaveThresholdModal.vue, src/store/modules/job/actions.ts, src/store/modules/product/actions.ts, src/store/modules/user/actions.ts, src/utils/index.ts
Closes #
[Screencast from Wednesday 31 August 2022 04:42:53  IST.webm](https://user-images.githubusercontent.com/62360781/187665957-5890ee69-a780-4cce-a55d-0da967f4d67c.webm)
=> Implemented: Modal to display server errors(#2gg32yc)

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
=> Updated bug report and feature request issue template

package-lock.json, package.json
=> Preparing for release 1.1.0

src/locales/en.json, src/views/ScheduleThreshold.vue
Closes #
After:
Desktop View:
Desktop View (Failed Status):
Mobile View:
=> Updated: styling for the schedule threshold page(#2dewjnh)

src/views/SelectProduct.vue
=> Updated grid layout of products on select product page(#2cxuh4m)

src/components/JobConfiguration.vue, src/components/Menu.vue, src/store/modules/user/actions.ts, src/views/SelectProduct.vue, src/views/ThresholdUpdates.vue
Closes #
- Only displaying select option if we have more than one product store Id
=> Added: support to change the product store from menu footer(#2e5w2hb)

src/components/Menu.vue
Closes #
Used outline icons in the sidebar menu for consistancy
Before:
After:
=> Updated: icons in menu to use outline icons

package-lock.json, package.json, release-notes.md
=> Updated: package.json, lock and release-notes file for major release(v2.0.0)

src/components/JobConfiguration.vue, src/locales/en.json, src/views/ScheduleThreshold.vue
=> Updated: label on schedule threshold page(#179)

package-lock.json, package.json, src/App.vue, src/adapter/index.ts, src/store/modules/user/actions.ts
As the emitter instance is different in oms api and app, the event are executed Based upon the new support in oms api to customize events, updated the code
Closes #
=> Fixed: navigation to login failed for token expire (oms-api#61)

package-lock.json, package.json, release-notes.md
=> Updated: package.json and lock file for patch release(v2.0.1)

src/components/JobConfiguration.vue, src/locales/en.json, src/views/ScheduleThreshold.vue
=> Fixed: issue of dateTime modal flicker effect when using trigger, also fixed the styling for dateTime modal

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for patch release(v.2.0.2)

src/views/ScheduleThreshold.vue
=> Fixed: jobs schedule and update not working after reordering jobs(#85zrnwg91)

package-lock.json, package.json, release-notes.md
=> Updated: release notes, package and lock file for patch release(v2.0.3)

package-lock.json, package.json, release-notes.md
=> Updated: release notes for patch release(2.0.4)

package-lock.json, package.json
=> Updated: app version for patch release (2.0.4)

src/services/UserService.ts, src/store/modules/product/actions.ts, src/store/modules/user/actions.ts, src/utils/index.ts
App should be accessed only by users with having role with product store
Fixed issue with product search, used catalogId instead of productStoreId
Closes #
=> Improved: Store specific access to the threshold app (#85zruaewr)

package-lock.json, package.json
=> Updated: app version for minor release (2.2.0)

package-lock.json, package.json
=> Updated: app version for minor release (2.3.0)

package-lock.json, package.json, release-notes.md
=> Updated: app version for minor release (2.4.0)

package-lock.json, package.json
=> Updated: package-lock and package file for minor release(v2.5.0)

package-lock.json, package.json
Closes #
Updated: package.json and package-lock.json for minor release (2.6.0)
=> Updated: package.json and package-lock.json for minor release (2.6.0)

package-lock.json, package.json
=> Updated: package.json and package-lock.json for the minor release (2.7.0)

package-lock.json, package.json, src/main.ts, src/views/Settings.vue, vue.config.js
Related Issue: https://github.com/hotwax/dxp-components/issues/177
Used the centralized oms instance navigator on the settings page which is implemented in dxp-components.
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change
=> Implemented: centralized oms instance navigator in settings page from dxp-components (#177)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v2.8.0)

src/views/ScheduleThreshold.vue
=> Fixed: Hidden item-divider when Channels are not found and Moved channel options at last of the list(#228)

src/store/modules/user/actions.ts
https://github.com/hotwax/dxp-components/issues/254
=> Fixed: Permission issue when defining a base permission for app(dxp-254)

src/components/ScheduleActionsPopover.vue, src/components/ScheduleRuleItem.vue
Related Issue #262
Added disabled check on schedule and disable action to disable them when not possible.
=> Improved: code to disable schedule actions when not required (#262)

src/main.ts
#226 
- Added a entry in `main` file to fix html tags not working in the translations.
=> Fixed: html tags not working in the translations (#226)

src/components/CreateGroupModal.vue, src/components/EditGroupModal.vue, src/components/FacilityItem.vue, src/components/LinkFacilitiesToGroupModal.vue, src/components/LinkThresholdFacilitiesToGroupModal.vue, src/components/RuleItem.vue, src/components/ScheduleActionsPopover.vue, src/components/ScheduleRuleItem.vue, src/components/SelectConfigFacilitiesModal.vue, src/components/UpdateFacilityGroupModal.vue, src/components/UpdateProductFiltersModal.vue, src/views/CreateSafetyStockRule.vue, src/views/CreateShippingRule.vue, src/views/CreateStorePickupRule.vue, src/views/CreateThresholdRule.vue, src/views/InventoryChannels.vue, src/views/SafetyStock.vue, src/views/Shipping.vue, src/views/StorePickup.vue, src/views/Threshold.vue
Related Issue #270
Implemented the loader while fetching or performing some actions all over the app.
=> Implemented: loader throughout the app where ever needed (#270)

src/components/AddProductFiltersModal.vue, src/components/UpdateProductFiltersModal.vue
Related Issue #271
Improved payload to be sent for fetching productFilters from solrFacets to allow pagination.
=> Fixed: offSet for fetching solrFacets to allow pagination (#271)

src/components/LinkFacilitiesToGroupModal.vue, src/components/LinkThresholdFacilitiesToGroupModal.vue, src/locales/en.json, src/views/CreateShippingRule.vue, src/views/CreateStorePickupRule.vue
Related Issue #278
- Improved the validation for checking mandatory fields while rule creation in case of Store pickup and Shipping.
- Improved payload to not fetch virtual facilites in link facilities to group modal.
=> Fixed: facility validation not working properly while store pickup and shipping rule creation (#278)

src/App.vue, src/store/modules/channel/actions.ts, src/store/modules/util/actions.ts
Related Issue #283
- Used pageSize for fetching records api.
- Reverted the app level check for filtering out expired records.
=> Improved: payload for fetching using pageSize and reverted app level check for expired records (#283)

src/api/index.ts, src/services/UserService.ts
Related Issue #297
Added support to login using the full oms url.
=> Improved: added support for login using full oms url (#297)

src/api/index.ts, src/components/SelectConfigFacilitiesModal.vue, src/components/UpdateFacilityGroupModal.vue, src/components/UpdateProductFiltersModal.vue, src/services/RuleService.ts, src/store/modules/rule/actions.ts, src/views/CreateSafetyStockRule.vue, src/views/CreateShippingRule.vue, src/views/CreateStorePickupRule.vue, src/views/CreateThresholdRule.vue
Related Issue #299
Used single api call to fetch both rules list along with their actions and conditions.
=> Improved: logic to fetch ruleActions and ruleConditions while fetching the rules for a group (#299)

src/components/RuleItem.vue, src/views/CreateSafetyStockRule.vue, src/views/CreateThresholdRule.vue
Related Issue #291
Fixed the validation to fix backspace not working on threshold value input.
=> Fixed: backspace not working on threshold value input (#291)

src/store/modules/util/actions.ts
Related Issue #310
Removed logic to use persisted facility groups.
=> Improved: logic to not use persisted facilityGroups (#310)

src/components/RuleItem.vue
Related Issue #317
Improved the styling of the rule card actions.
Before
After
=> Improved: styling of the rule card for better user interface. (#317)

src/views/InventoryChannels.vue
Related Issue #291
Improved logic to fetch count of group facilities.
=> Improved: logic to get count of facilities associated with a group (#291)

src/views/SafetyStock.vue, src/views/Shipping.vue, src/views/StorePickup.vue, src/views/Threshold.vue
Related Issue #287
Related Comment https://github.com/hotwax/threshold-management/issues/287#issuecomment-2125572407
Fixed the empty state message displayed in case of all the rules are archived.
=> Improved: fixed the empty state message in rule pages (#287)

src/components/OrderLimitPopover.vue, src/components/RuleGroupHistoryModal.vue, src/components/RuleItem.vue, src/components/ScheduleActionsPopover.vue, src/components/ScheduleRuleItem.vue, src/views/CreateUpdateSafetyStockRule.vue, src/views/CreateUpdateShippingRule.vue, src/views/CreateUpdateStorePickupRule.vue, src/views/CreateUpdateThresholdRule.vue
Related Issue #328
- Improved line bottomsi in rule card and schedule card.
- Fixed orderLimitPopover value updation issue.
- Fixed ruleGroup runtime history fetching issue.
=> Fixed: lines bottom in rule card and schedule card, ruleGroup run history fetching issue, and orderLimit updating issue (#328)

.firebaserc, src/components/CreateGroupModal.vue, src/locales/en.json
Related Issue #333
- Showed error message from the server while inventory channel creation.
- Improved firebase entries for the atp app deployment.
Before
After
=> Improved: showed error message from the server while inventory channel creation and updated firebase configuration (#333)

src/components/RuleItem.vue, src/locales/en.json, src/services/UtilService.ts, src/store/modules/channel/actions.ts, src/store/modules/util/actions.ts, src/utils/index.ts, src/views/CreateUpdateSafetyStockRule.vue, src/views/CreateUpdateShippingRule.vue, src/views/CreateUpdateStorePickupRule.vue, src/views/CreateUpdateThresholdRule.vue, src/views/Settings.vue
Related Issue #347
Added a toggle for selecting all the facility groups and facilities.
=> Implemented: support for all facilities/channels selection while rule creation and updation (#347)

package-lock.json, package.json
=> Updated: app version for the patch release (v3.0.1)

.github/PULL_REQUEST_TEMPLATE.md, README.md, capacitor.config.json, manifest.json, package-lock.json, package.json, public/index.html
Related Issue #350
Updated the app title and other name entries to "Available to Promise"
=> Improved: app title to 'Available to Promise' (#350)

package-lock.json, package.json
=> Updated: app version for the patch release (v3.0.2)

package-lock.json, package.json
=> Updated: app version for the minor release (v3.1.0)

src/locales/en.json, src/store/modules/channel/actions.ts, src/views/InventoryChannels.vue, src/views/StorePickup.vue
#354
- Added empty state message in case of no publish jobs, and no store pickup groups.
- Improved the config fetching post product store change from menu footer navigation.
=> Improved: added empty state in case of no jobs and no store pickup groups, and fixed issue in group fetching (#354)

src/components/RuleItem.vue, src/utils/index.ts, src/views/CreateUpdateSafetyStockRule.vue, src/views/CreateUpdateShippingRule.vue, src/views/CreateUpdateStorePickupRule.vue
#371
Used in/not-in operator in the rule generation and rendering for the selected facilities or channels
=> Improved: operator to be used in rule condition for facilities / channels selection (#371)

package-lock.json, package.json
#
Updated: app version for patch release (v3.1.1)
=> Updated: app version for patch release (v3.1.1)

package-lock.json, package.json
=> Updated: app version for patch release v3.1.2

package-lock.json, package.json
=> Updated: app version for patch release v3.1.3

package-lock.json, package.json
=> Updated: app version for minor release v3.2.0
